### ISSUE TITLE
STAR 

### ISSUE THREAD

**Issue by vetmohit89** [cougarlj/COMPSRA#49]
Hello, 

I am working on university HPC cluster and they already have loaded module STAR using  module load STAR/2.7.3a-GCC-6.4.0-2.28 command. Then trying to run java -jar COMPSRA.jar -ref hg38 -aln -mt STAR -mbi -in ./example_out/sample01/sample01_17to50_FitRead.fastq.gz -out ./example_out/sample01/sample01_17to50_FitRead... 

It is not working. Can you please help. 

Thanks

**Comment by criphg** [comment]
I am also having problems with star. I have star 2.7.10 previous installed and I can´t make the alignment even using the example:

+++++++++++++++++++++++++++++++
+            COMPSRA          +
+     (V1.0.2 2020-07-03)     +
+  rejia@channing.harvard.edu +
+++++++++++++++++++++++++++++++


Working Directory: /home/yanlab/Tools/COMPSRA
Bundle Directory: /home/yanlab/Tools/COMPSRA/bundle_v1
Configuration Directory: /home/yanlab/Tools/COMPSRA/bundle_v1/configuration
Plug Directory: /home/yanlab/Tools/COMPSRA/bundle_v1/plug
N_CPU: 64

Configuration Info: The endogenous database configuration has been set!
Configuration Info: 37 databases are set!
17:12:25.171 [main] INFO  edu.harvard.channing.compass.core.Configuration - The Configuration was completed!

The hg38 reference genome was set.
QC module will not be performed.
The hg38 was set in default.
Annotation module will not be performed.
Microbe module will not be performed.
Function module will not be performed.

+++++++++++++++++++++++++++++++
+    Module  --->  Alignment  +
+++++++++++++++++++++++++++++++

17:12:25.182 [main] ERROR java.lang.Class - STAR was not installed correctly!

**Comment by cougarlj** [comment]
Sorry for the late reply. To simplify the use of COMPSRA, we fixed the directory of STAR in /bundle_v1/plug/star/STAR-2.5.3a/bin/Linux_x86_64/STAR. For COMPSRA v1, it doesn't support changing the directory of STAR. A feasible way is that you can copy the STAR file into this directory. It should be fine because I have done this.

**Comment by criphg** [comment]
Sorry, I try to copy my STAR file for the directory but still not work for me, same error. Also when I try download STAR-2.5.3a using the function or wget the zip file come truncated.

java -jar COMPSRA.jar -tk -dr -ck star

+++++++++++++++++++++++++++++++
+            COMPSRA          +
+     (V1.0.2 2020-07-03)     +
+  rejia@channing.harvard.edu +
+++++++++++++++++++++++++++++++


Working Directory: /home/yanlab/Tools/COMPSRA
Bundle Directory: /home/yanlab/Tools/COMPSRA/bundle_v1
Configuration Directory: /home/yanlab/Tools/COMPSRA/bundle_v1/configuration
Plug Directory: /home/yanlab/Tools/COMPSRA/bundle_v1/plug
N_CPU: 64

Configuration Info: The endogenous database configuration has been set!
Configuration Info: 37 databases are set!
14:11:28.031 [main] INFO  edu.harvard.channing.compass.core.Configuration - The Configuration was completed!


+++++++++++++++++++++++++++++++
+      COMPASS ---> ToolKit   +
+++++++++++++++++++++++++++++++

14:11:28.037 [main] INFO  edu.harvard.channing.compass.utility.Download - Start to download the resource: https://regepi.bwh.harvard.edu/circurna/bundle_v1/plug/star/STAR-2.5.3a.zip
14:11:28.784 [main] INFO  edu.harvard.channing.compass.utility.Download - Finish to download the resource: https://regepi.bwh.harvard.edu/circurna/bundle_v1/plug/star/STAR-2.5.3a.zip
14:11:28.795 [main] ERROR edu.harvard.channing.compass.utility.DeCompress - Fail to uncompress the file /home/yanlab/Tools/COMPSRA/bundle_v1/plug/star/STAR-2.5.3a.zip
14:11:28.796 [main] ERROR edu.harvard.channing.compass.utility.DeCompress - zip END header not found
14:11:28.796 [main] INFO  edu.harvard.channing.compass.utility.Download - File /home/yanlab/Tools/COMPSRA/bundle_v1/plug/star/STAR-2.5.3a.zip was uncompressed.
14:11:28.796 [main] INFO  edu.harvard.channing.compass.core.Produce - ToolKit module was completed.

**Comment by cougarlj** [comment]
It seemed that the IT group moved the STAR resource to another place. You
can download STAR from the official website (Source code(zip)
<https://github.com/alexdobin/STAR/archive/refs/tags/2.5.3a.zip>
https://github.com/alexdobin/STAR/archive/refs/tags/2.5.3a.zip) and
decompressed it in the related directory. If any problem, please let me
know.

**Comment by mchiconb** [comment]
Hi,
I've been following this thread as I encountered the same problem when installing/decompressing STAR. I tried downloading STAR2.5.3a from the link provided and placing all the decompressed files inside bundle_v1/plug/star/ but still get the 'STAR was not installed correctly!' error. Can you provided some further help or screenshots? 

Thanks a lot,
Mariona

**Comment by pseudacriscrucifer** [comment]
@mchiconb any update / solution to this? Sounds like a similar issue I am facing with uncompressing STAR 2.5.3a to /path (#53)
